apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: calculator
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 40.81.242.220
      ipMode: VIP
